# Generated by Django 5.1.15 on 2026-10-08 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_seed_default_categories'),
        ('transactions', '0006_backfill_transfer_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_digest', models.CharField(max_length=64)),
                ('profile', models.CharField(max_length=32)),
                ('parser_version', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('account_hint', models.CharField(blank=True, max_length=16)),
                ('account_identity', models.CharField(max_length=32)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('page_count', models.PositiveIntegerField()),
                ('checks', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StatementRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('component', models.CharField(choices=[('principal', 'Principal'), ('fee', 'Fee')], max_length=16)),
                ('extracted', models.JSONField()),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('value_date', models.DateField(null=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('fee', 'Fee'), ('refund', 'Refund'), ('lend', 'Lend'), ('borrow', 'Borrow'), ('repayment_received', 'Repayment received'), ('repayment_paid', 'Repayment paid')], max_length=32)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('counterparty_text', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('classification_confirmed', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Added'), ('linked', 'Linked'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='statements.statementimport')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('other_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statement_counterparties', to='accounts.account')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_rows', to='transactions.transaction')),
            ],
            options={
                'ordering': ('position', '-component', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='statementimport',
            index=models.Index(fields=['user', 'created_at'], name='statements__user_id_13a8fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='statementimport',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'file_digest'), name='statement_file_per_account'),
        ),
        migrations.AddIndex(
            model_name='statementrow',
            index=models.Index(fields=['batch', 'state'], name='statements__batch_i_04309d_idx'),
        ),
        migrations.AddConstraint(
            model_name='statementrow',
            constraint=models.UniqueConstraint(fields=('batch', 'position', 'component'), name='statement_component_per_row'),
        ),
        migrations.AddConstraint(
            model_name='statementrow',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('batch', 'transaction'), name='statement_movement_per_batch'),
        ),
    ]
