# Generated by Codex for the initial finance API schema.

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("home_cash", "Home cash"),
                            ("mobile_wallet", "Mobile wallet"),
                            ("bank", "Bank"),
                            ("credit_card", "Credit card"),
                            ("savings", "Savings"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "starting_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_account_name_per_user",
                    )
                ],
            },
        ),
    ]

