# Generated by Django 5.2.1 on 2026-05-30 22:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('transactions', '0002_rename_transactio_user_id_453ccf_idx_transaction_user_id_8af7f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=32)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=32)),
                ('auto_create_transaction', models.BooleanField(default=False)),
                ('reminder_days_before', models.PositiveIntegerField(default=3)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bills', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bills', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('next_due_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RecurringBillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('paid_at', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='recurring_bills.recurringbill')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bill_payments', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['user', 'status'], name='recurring_b_user_id_09f9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['user', 'next_due_date'], name='recurring_b_user_id_74759e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['account', 'status'], name='recurring_b_account_700dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbillpayment',
            index=models.Index(fields=['user', 'paid_at'], name='recurring_b_user_id_26398a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbillpayment',
            index=models.Index(fields=['bill', 'due_date'], name='recurring_b_bill_id_b661c6_idx'),
        ),
    ]
