#!/usr/bin/env python3
"""Generate a small TypeScript API client from the shared OpenAPI contract."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
OPENAPI_FILE = ROOT / "openapi.yaml"
GENERATED_DIR = ROOT / "generated"
TYPES_FILE = GENERATED_DIR / "types.ts"
CLIENT_FILE = GENERATED_DIR / "client.ts"


def pascal_case(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^a-zA-Z0-9]+", value) if part)


def camel_case(value: str) -> str:
    pascal = pascal_case(value)
    return pascal[:1].lower() + pascal[1:] if pascal else "request"


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def schema_ref_name(ref: str) -> str:
    return ref.rsplit("/", maxsplit=1)[-1]


def ts_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "unknown"

    nullable = schema.get("nullable") is True
    if "$ref" in schema:
        base = schema_ref_name(schema["$ref"])
    elif "allOf" in schema:
        parts = [ts_type(part) for part in schema["allOf"]]
        base = " & ".join(parts) if parts else "unknown"
    elif "oneOf" in schema or "anyOf" in schema:
        key = "oneOf" if "oneOf" in schema else "anyOf"
        base = " | ".join(ts_type(part) for part in schema[key])
    elif "enum" in schema:
        base = " | ".join(
            str(value).lower() if isinstance(value, (bool, int, float)) else quote(str(value))
            for value in schema["enum"]
        )
    else:
        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            return " | ".join(ts_type({**schema, "type": item}) for item in schema_type)
        if schema_type == "string" and schema.get("format") == "binary":
            base = "Blob"
        elif schema_type == "array":
            base = f"{ts_type(schema.get('items'))}[]"
        elif schema_type == "boolean":
            base = "boolean"
        elif schema_type in {"integer", "number"}:
            base = "number"
        elif schema_type == "object":
            properties = schema.get("properties", {})
            additional = schema.get("additionalProperties")
            if properties:
                required = set(schema.get("required", []))
                lines = ["{"]
                for property_name, property_schema in properties.items():
                    optional = "" if property_name in required else "?"
                    lines.append(f"  {property_name}{optional}: {ts_type(property_schema)};")
                lines.append("}")
                base = "\n".join(lines)
            elif isinstance(additional, dict):
                base = f"Record<string, {ts_type(additional)}>"
            else:
                base = "Record<string, unknown>"
        else:
            base = "string"

    return f"{base} | null" if nullable else base


def response_type(operation: dict[str, Any]) -> str:
    responses = operation.get("responses", {})
    for status in ("200", "201", "204"):
        response = responses.get(status)
        if not response:
            continue
        content = response.get("content", {})
        if "application/json" in content:
            return ts_type(content["application/json"].get("schema"))
        if "text/csv" in content:
            return "Blob"
        if status == "204":
            return "void"
    return "unknown"


def request_body_type(operation: dict[str, Any]) -> str | None:
    content = operation.get("requestBody", {}).get("content", {})
    if "multipart/form-data" in content:
        return "FormData"
    if "application/json" not in content:
        return None
    return ts_type(content["application/json"].get("schema"))


def path_parameters(path: str) -> list[str]:
    return re.findall(r"{([^}]+)}", path)


def query_parameter_type(operation: dict[str, Any]) -> str | None:
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]
    if not query_params:
        return None
    lines = ["{"]
    for param in query_params:
        lines.append(f"  {param['name']}?: {ts_type(param.get('schema'))};")
    lines.append("}")
    return "\n".join(lines)


def method_name(method: str, path: str, operation: dict[str, Any], used_names: set[str]) -> str:
    summary = operation.get("summary")
    base = camel_case(summary or f"{method} {path}")
    name = base
    suffix = 2
    while name in used_names:
        name = f"{base}{suffix}"
        suffix += 1
    used_names.add(name)
    return name


def generate_types(openapi: dict[str, Any]) -> str:
    schemas = openapi["components"]["schemas"]
    chunks = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_ts_client.py. Do not edit by hand.",
        "",
    ]

    for name, schema in schemas.items():
        if schema.get("type") == "object" and schema.get("properties"):
            required = set(schema.get("required", []))
            chunks.append(f"export interface {name} {{")
            for property_name, property_schema in schema["properties"].items():
                optional = "" if property_name in required else "?"
                chunks.append(f"  {property_name}{optional}: {ts_type(property_schema)};")
            chunks.append("}")
        else:
            chunks.append(f"export type {name} = {ts_type(schema)};")
        chunks.append("")

    return "\n".join(chunks).rstrip() + "\n"


def generate_client(openapi: dict[str, Any]) -> str:
    used_names: set[str] = set()
    methods: list[str] = []
    imports: set[str] = set()

    for path, path_item in openapi["paths"].items():
        for method, operation in path_item.items():
            if method not in {"get", "post", "patch", "delete", "put"}:
                continue
            name = method_name(method, path, operation, used_names)
            return_type = response_type(operation)
            body_type = request_body_type(operation)
            query_type = query_parameter_type(operation)
            params = path_parameters(path)
            for type_name in re.findall(r"\b[A-Z][A-Za-z0-9_]+\b", f"{return_type} {body_type or ''} {query_type or ''}"):
                if type_name not in {"Blob", "FormData"}:
                    imports.add(type_name)

            signature_parts: list[str] = []
            if params:
                signature_parts.append("pathParams: {" + "; ".join(f"{param}: string" for param in params) + " }")
            if query_type:
                signature_parts.append(f"query?: {query_type}")
            if body_type:
                signature_parts.append(f"body: {body_type}")
            signature = ", ".join(signature_parts)

            url_expr = quote(path)
            if params:
                for param in params:
                    url_expr += f".replace('{{{param}}}', encodeURIComponent(pathParams.{param}))"

            request_options = [f"method: {quote(method.upper())}"]
            if body_type:
                request_options.append("body")
            if query_type:
                request_options.append("query")

            methods.append(
                "\n".join(
                    [
                        f"  async {name}({signature}): Promise<{return_type}> {{",
                        f"    return this.request<{return_type}>({url_expr}, {{ {', '.join(request_options)} }});",
                        "  }",
                    ]
                )
            )

    import_line = ""
    if imports:
        import_line = f"import type {{ {', '.join(sorted(imports))} }} from './types';\n\n"

    return (
        "/* eslint-disable */\n"
        "// Generated by scripts/generate_ts_client.py. Do not edit by hand.\n\n"
        f"{import_line}"
        "export type ApiClientConfig = {\n"
        "  accessToken?: string;\n"
        "  baseUrl: string;\n"
        "};\n\n"
        "type RequestOptions = {\n"
        "  body?: unknown;\n"
        "  method: string;\n"
        "  query?: Record<string, string | number | boolean | null | undefined>;\n"
        "};\n\n"
        "export class FinanceApiClient {\n"
        "  private readonly config: ApiClientConfig;\n\n"
        "  constructor(config: ApiClientConfig) {\n"
        "    this.config = config;\n"
        "  }\n\n"
        "  private async request<T>(path: string, options: RequestOptions): Promise<T> {\n"
        "    const url = new URL(path, this.config.baseUrl);\n"
        "    for (const [key, value] of Object.entries(options.query ?? {})) {\n"
        "      if (value !== undefined && value !== null && value !== '') {\n"
        "        url.searchParams.set(key, String(value));\n"
        "      }\n"
        "    }\n\n"
        "    const headers: Record<string, string> = {};\n"
        "    if (this.config.accessToken) {\n"
        "      headers.Authorization = `Bearer ${this.config.accessToken}`;\n"
        "    }\n"
        "    const isMultipart = typeof FormData !== 'undefined' && options.body instanceof FormData;\n"
        "    if (options.body !== undefined && !isMultipart) {\n"
        "      headers['Content-Type'] = 'application/json';\n"
        "    }\n\n"
        "    const response = await fetch(url, {\n"
        "      body: isMultipart ? options.body as FormData : options.body === undefined ? undefined : JSON.stringify(options.body),\n"
        "      headers,\n"
        "      method: options.method,\n"
        "    });\n\n"
        "    if (!response.ok) {\n"
        "      throw new Error(`Request failed with HTTP ${response.status}.`);\n"
        "    }\n"
        "    if (response.status === 204) {\n"
        "      return undefined as T;\n"
        "    }\n"
        "    const contentType = response.headers.get('content-type') ?? '';\n"
        "    if (contentType.includes('text/csv')) {\n"
        "      return (await response.blob()) as T;\n"
        "    }\n"
        "    return (await response.json()) as T;\n"
        "  }\n\n"
        + "\n\n".join(methods)
        + "\n"
        "}\n"
    )


def main() -> None:
    openapi = yaml.safe_load(OPENAPI_FILE.read_text())
    GENERATED_DIR.mkdir(exist_ok=True)
    TYPES_FILE.write_text(generate_types(openapi))
    CLIENT_FILE.write_text(generate_client(openapi))
    print(f"Generated {TYPES_FILE.relative_to(ROOT)} and {CLIENT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
