/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. Keep it committed so TypeScript tooling
// works before the first local dev run.

