# Generated by Django 5.2.1 on 2026-05-30 21:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_rename_transactio_user_id_453ccf_idx_transaction_user_id_8af7f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_due', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statement_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=32)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_card_bills', to='accounts.account')),
                ('statement_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_bills', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_at', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit_cards.creditcardbill')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_payments', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='creditcardbill',
            index=models.Index(fields=['user', 'status'], name='credit_card_user_id_145108_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardbill',
            index=models.Index(fields=['user', 'due_date'], name='credit_card_user_id_e7c693_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardbill',
            index=models.Index(fields=['account', 'status'], name='credit_card_account_862b04_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardpayment',
            index=models.Index(fields=['user', 'paid_at'], name='credit_card_user_id_82237a_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardpayment',
            index=models.Index(fields=['bill', 'paid_at'], name='credit_card_bill_id_82c9f9_idx'),
        ),
    ]
