# Generated by Codex for the initial finance API schema.

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("income", "Income"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Adjustment"),
                            ("fee", "Fee"),
                            ("refund", "Refund"),
                            ("lend", "Lend"),
                            ("borrow", "Borrow"),
                            ("repayment_received", "Repayment received"),
                            ("repayment_paid", "Repayment paid"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                            ("sms", "SMS"),
                            ("import", "Import"),
                            ("system", "System"),
                        ],
                        default="web",
                        max_length=32,
                    ),
                ),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="categories.category",
                    ),
                ),
                (
                    "transfer_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "-created_at"),
                "indexes": [
                    models.Index(fields=("user", "date"), name="transactio_user_id_453ccf_idx"),
                    models.Index(fields=("user", "type"), name="transactio_user_id_4c8f83_idx"),
                ],
            },
        ),
    ]

