# Generated by Django 5.2.1 on 2026-05-30 21:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('finance_messages', '0005_related_transfer_candidate'),
        ('payment_methods', '0002_provider_choices'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_8af7f1_idx',
            old_name='transactio_user_id_453ccf_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_4685bf_idx',
            old_name='transactio_user_id_4c8f83_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_key',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment_methods.paymentmethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance_messages.rawmessage'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'direction'], name='transaction_user_id_345150_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'reference'], name='transaction_user_id_40992e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'external_key'], name='transaction_user_id_e28f5d_idx'),
        ),
    ]
