# Generated by Django 5.1.15 on 2026-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_card_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_card_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
