# Generated by Django 5.2.1 on 2026-05-29 22:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField()),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expected_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('missing_money', 'Missing money'), ('extra_money', 'Extra money'), ('adjusted', 'Adjusted'), ('ignored', 'Ignored')], default='matched', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='accounts.account')),
                ('adjustment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_snapshot_adjustments', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-checked_at', '-created_at'),
                'indexes': [models.Index(fields=['user', 'account', 'checked_at'], name='reconciliat_user_id_a6bb89_idx'), models.Index(fields=['user', 'status'], name='reconciliat_user_id_cb8a3b_idx')],
            },
        ),
    ]
