# Generated by Codex for Phase 2 payment method management.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                            ("city_bank", "City Bank"),
                            ("bank", "Bank"),
                            ("card", "Card"),
                            ("manual", "Manual"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_methods",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_payment_method_name_per_user",
                    )
                ],
            },
        ),
    ]
