# Generated by Codex for Phase 3 provider coverage.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_methods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="provider",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("rocket", "Rocket"),
                    ("ebl", "EBL"),
                    ("city_bank", "City Bank"),
                    ("pathao_pay", "Pathao Pay"),
                    ("bank", "Bank"),
                    ("card", "Card"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
