# Generated by Django 5.1.15 on 2026-10-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_provider_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='additional_identifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='identifier_kind',
            field=models.CharField(choices=[('any', 'Unspecified'), ('account', 'Account'), ('card', 'Card')], default='any', max_length=16),
        ),
    ]
