# Generated by Codex for Phase 2 SMS sender rule management.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("payment_methods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SenderRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                            ("city_bank", "City Bank"),
                            ("bank", "Bank"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sender", models.CharField(max_length=120)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("regex", "Regex"),
                        ],
                        default="exact",
                        max_length=32,
                    ),
                ),
                ("pattern", models.CharField(blank=True, max_length=255)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sender_rules",
                        to="accounts.account",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sender_rules",
                        to="payment_methods.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "name"),
                "indexes": [
                    models.Index(fields=("user", "sender"), name="finance_mes_user_id_51a945_idx"),
                    models.Index(fields=("user", "provider"), name="finance_mes_user_id_ad7617_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_sender_rule_name_per_user",
                    )
                ],
            },
        ),
    ]
