# Generated by Codex for Phase 2 raw SMS import tracking.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("received_at", models.DateTimeField()),
                ("device_message_id", models.CharField(blank=True, max_length=120)),
                ("body_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("duplicate", "Duplicate"),
                            ("ignored", "Ignored"),
                        ],
                        default="imported",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="finance_messages.rawmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at", "-created_at"),
                "indexes": [
                    models.Index(fields=("user", "sender"), name="finance_mes_user_id_b8313a_idx"),
                    models.Index(fields=("user", "received_at"), name="finance_mes_user_id_809415_idx"),
                    models.Index(fields=("user", "body_hash"), name="finance_mes_user_id_434e87_idx"),
                    models.Index(fields=("user", "device_message_id"), name="finance_mes_user_id_08d3db_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "body_hash"),
                        name="unique_raw_message_hash_per_user",
                    )
                ],
            },
        ),
    ]
