# Generated by Django 5.2.1 on 2026-05-29 20:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance_messages', '0002_rawmessage'),
        ('payment_methods', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedMessageCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('fee', 'Fee'), ('refund', 'Refund')], default='expense', max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='needs_review', max_length=32)),
                ('parser_name', models.CharField(blank=True, max_length=120)),
                ('parser_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parsed_message_candidates', to='accounts.account')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_message_candidates', to='payment_methods.paymentmethod')),
                ('raw_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='finance_messages.rawmessage')),
                ('sender_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_candidates', to='finance_messages.senderrule')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_message_candidates', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_message_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='finance_mes_user_id_4244ad_idx'), models.Index(fields=['user', 'created_at'], name='finance_mes_user_id_6d592a_idx')],
            },
        ),
    ]
