# Generated by Codex for Phase 3 transfer-aware SMS parsing.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("finance_messages", "0003_parsedmessagecandidate"),
        ("payment_methods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senderrule",
            name="provider",
            field=models.CharField(
                choices=[
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("rocket", "Rocket"),
                    ("ebl", "EBL"),
                    ("city_bank", "City Bank"),
                    ("pathao_pay", "Pathao Pay"),
                    ("bank", "Bank"),
                    ("card", "Card"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="balance_after",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="counterparty_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="destination_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_parsed_message_candidates",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="destination_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_parsed_message_candidates",
                to="payment_methods.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="fee_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="message_kind",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("cash_in", "Cash in"),
                    ("cash_out", "Cash out"),
                    ("send_money", "Send money"),
                    ("receive_money", "Receive money"),
                    ("bank_transfer_in", "Bank transfer in"),
                    ("bank_transfer_out", "Bank transfer out"),
                    ("card_purchase", "Card purchase"),
                    ("card_payment", "Card payment"),
                    ("fee", "Fee"),
                    ("refund", "Refund"),
                    ("reversal", "Reversal"),
                    ("balance_notice", "Balance notice"),
                    ("otp_or_security", "OTP or security"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="possible_internal_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("rocket", "Rocket"),
                    ("ebl", "EBL"),
                    ("city_bank", "City Bank"),
                    ("pathao_pay", "Pathao Pay"),
                    ("bank", "Bank"),
                    ("card", "Card"),
                    ("other", "Other"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
