# Generated by Codex for Phase 3 internal transfer matching hints.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_messages", "0004_parser_transfer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="possible_related_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_candidates",
                to="finance_messages.parsedmessagecandidate",
            ),
        ),
        migrations.AddField(
            model_name="parsedmessagecandidate",
            name="related_match_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
