# Generated by Django 5.2.1 on 2026-05-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_messages', '0005_related_transfer_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessage',
            name='redacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmessage',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored'), ('redacted', 'Redacted')], default='imported', max_length=32),
        ),
    ]
