# Generated by Django 5.2.1 on 2026-09-30 16:50

import apps.messages.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_messages', '0007_sender_rule_case_insensitive_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='rejection_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('not_transaction', 'Not a transaction'), ('otp_security', 'OTP or security message'), ('duplicate', 'Duplicate'), ('wrong_provider_account', 'Wrong provider or account'), ('personal', 'Personal or non-financial'), ('unsupported_format', 'Unsupported format'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='exclusion_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='message_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='provider',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('ebl', 'EBL'), ('city_bank', 'City Bank'), ('pathao_pay', 'Pathao Pay'), ('bank', 'Bank'), ('card', 'Card'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='SmsCapturePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excluded_providers', models.JSONField(blank=True, default=list)),
                ('excluded_message_kinds', models.JSONField(blank=True, default=apps.messages.models.default_excluded_message_kinds)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_capture_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
