# Generated by Django 5.1.15 on 2026-10-03 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_seed_default_categories'),
        ('finance_messages', '0009_sms_device_status_retention_and_learning'),
        ('payment_methods', '0002_provider_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='receiver_account_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='receiver_card_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='sender_account_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='sender_card_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='SenderRuleMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_kind', models.CharField(max_length=32)),
                ('transaction_type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_rule_mappings', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_rule_mappings', to='categories.category')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_rule_mappings', to='payment_methods.paymentmethod')),
                ('sender_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_mappings', to='finance_messages.senderrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_rule_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sender_rule', 'message_kind'),
                'constraints': [models.UniqueConstraint(fields=('sender_rule', 'message_kind'), name='unique_mapping_per_sender_rule_kind')],
            },
        ),
    ]
