# Generated by Django 5.1.15 on 2026-10-07 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_seed_default_categories'),
        ('finance_messages', '0010_parsedmessagecandidate_receiver_account_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='suggested_transfer_direction',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='parsedmessagecandidate',
            name='transfer_suggestion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TransferCounterpartyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_kind', models.CharField(max_length=32)),
                ('counterparty_key', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('other_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_transfer_mappings', to='accounts.account')),
                ('reporting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_transfer_mappings', to='accounts.account')),
                ('sender_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_messages.senderrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'sender_rule', 'message_kind', 'reporting_account', 'counterparty_key'), name='unique_transfer_counterparty_path')],
            },
        ),
    ]
