# Generated by Django 5.1.15 on 2026-10-07 18:23

from django.db import migrations, models


def enable_promotional_skip(apps, schema_editor):
    Preference = apps.get_model("finance_messages", "SmsCapturePreference")
    for preference in Preference.objects.using(schema_editor.connection.alias).all().iterator():
        if "promotional" not in preference.excluded_message_kinds:
            preference.excluded_message_kinds = [*preference.excluded_message_kinds, "promotional"]
            preference.save(using=schema_editor.connection.alias, update_fields=("excluded_message_kinds",))


def disable_promotional_skip(apps, schema_editor):
    Preference = apps.get_model("finance_messages", "SmsCapturePreference")
    for preference in Preference.objects.using(schema_editor.connection.alias).all().iterator():
        preference.excluded_message_kinds = [kind for kind in preference.excluded_message_kinds if kind != "promotional"]
        preference.save(using=schema_editor.connection.alias, update_fields=("excluded_message_kinds",))


class Migration(migrations.Migration):

    dependencies = [
        ('finance_messages', '0011_transfer_counterparty_suggestions'),
    ]

    operations = [
        migrations.RunPython(enable_promotional_skip, disable_promotional_skip),
        migrations.AlterField(
            model_name='parsedmessagecandidate',
            name='message_kind',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('cash_in', 'Cash in'), ('cash_out', 'Cash out'), ('send_money', 'Send money'), ('receive_money', 'Receive money'), ('bank_transfer_in', 'Bank transfer in'), ('bank_transfer_out', 'Bank transfer out'), ('card_purchase', 'Card purchase'), ('card_payment', 'Card payment'), ('fee', 'Fee'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('balance_notice', 'Balance notice'), ('otp_or_security', 'OTP or security'), ('promotional', 'Promotional offers'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
